name: My Calculation Workflow     # Workflow name 
 
on: push            # Triggered on every push 
 
jobs: 
  print:
    runs-on: ubuntu-latest 

    steps: 
      - run: |
          result=$(expr 2 + 2)
          echo "2 + 2 = $result"
