name: My First Workflow     # Workflow name 
 
on: push            # Triggered on every push 
 
jobs: 
  print:
    runs-on: ubuntu-latest 

    steps: 
      - name: Testing phase
        run: echo "testing"