name: My First Workflow     # Workflow name 
 
on: push            # Triggered on every push 
 
jobs: 
  Build:
    runs-on: ubuntu-latest 

    steps: 
      - name: Code Checkout Repo
        uses: actions/checkout@v5

      - name: Building
        run: echo "building...."
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Testing
        run: echo "testing"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment
        run: echo "Deploying..."
        